### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Samson11** [scientisst/scientisst_db#1]
Please can you make it compatible with flutter null safety.
Thank you.

**Comment by johannphilippe** [comment]
Hope it could be done too ! 
Great work by the way !

**Comment by afonsocraposo** [comment]
Sorry for the delay in answering this. I'll be reviewing everything in the next days.

**Comment by afonsocraposo** [comment]
I fixed the null safety issues.
Please use version `0.1.2`.
Again, I'm sorry for the delay!
