### ISSUE TITLE
Nested list cannot contain elements that do not exist in parent document

### ISSUE THREAD

**Issue by elycabrall** [scientisst/scientisst_db#3]
Example:

if my document is:
{
"id":"123",
"name":"Ely",
"contacts":[{
  "id": "2323343",
  "email":"elyjrcabral@gmail.com"
}]
}

will return an error because the email key does not exist in the root, but when removing the email, the list will return the nested id

**Comment by afonsocraposo** [comment]
Sorry for the delay in answering this. I'll be reviewing everything in the next days.

**Comment by afonsocraposo** [comment]
I fixed the json encoding problems.
Please use version `0.1.2`.
Again, I'm sorry for the delay!
