### ISSUE TITLE
there is some issues in null safe please fix it

### ISSUE THREAD

**Issue by iamirzashowvik** [scientisst/scientisst_db#4]

**Comment by elycabrall** [comment]
use

scientisst_db:
    git:
      url: https://github.com/elycabrall/scientisst_db.git

**Comment by afonsocraposo** [comment]
Sorry for the delay in answering this. I'll be reviewing everything in the next days.

**Comment by afonsocraposo** [comment]
I fixed the null safety issues.
Please use version `0.1.2`.
Again, I'm sorry for the delay!
